[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

; 16 MB Flash + 8 MB Octal PSRAM
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0